### ISSUE TITLE
[Bug]: XML "version" root projectnode config interprets version numbers not as strings

### ISSUE THREAD

**Issue by garvinhicking** [phpDocumentor/guides#1057]
### Summary

Original issue: https://github.com/TYPO3-Documentation/render-guides/issues/694

If an extension releases version 1.10 (2 digits as minor version), with the new rendering the second digit is missing both in the overview and in the selected item in the version switcher.

I boiled this down to:

- `src/Config/XmlFileLoader.php` -> `load()` uses `symfony/config/XmlUtils` to parse the XML files
- `symfony/config/XmlUtils::convertDomElementToArray()` which uses a native PHP DomElement
- That method uses `phpize` to convert all object values
- That converts "1.10" to probably be recognized as a float and thus shortened to "1.1"

There is code in `/src/DependencyInjection/GuidesExtension.php` -> `getConfigTreeBuilder`:

```
                        ->scalarNode('version')
                            ->beforeNormalization()
                            ->always(
                                // We need to revert the phpize call in XmlUtils. Version is always a string!
                                static function ($value) {
                                    if (!is_int($value) && !is_string($value)) {
                                        return var_export($value, true);
                                    }

                                    return $value;
                                },
                            )
```

The type passed here is "d:1.1", so a double.

I do not think we can easily undo that double though, because all these values get resolved to "d:1.1":

* 1.1
* 1.10
* 1.100
* 1.1000
* Bonus: "1.0" gets converted to just "1".

and so on. So we can never go "back" from the php-ized version here.

It does not seem the XmlUtils symfony package allows to bypass or configure phpize. Ideas:

* post-fix the version differently and access it from the DomElement XML natively, and overwrite the "version" thing. So we fix it for one specific known key. We might face other numerical cast issues though down the road?
* make our own `XmlUtils::convertDomElementToArray` logic here that does not do float/double parsing? That's redundance of course, so maybe we pass along this issue to Symfony/Config? ...

Looking forward to input :)

### Code snippet that reproduces the problem

Example: https://docs.typo3.org/p/praetorius/vite-asset-collector/1.10/en-us/

### Expected output

Seing "1.10" as version, and not "1.1".

**Comment by jaapio** [comment]
This seems to be an issue in symfony. I think it will be very hard to solve. So decided to introduce an escape syntax using single quotes. So the value is always seen as a string.

**Comment by garvinhicking** [comment]
Many thanks, cool idea. However, do I understand properly - we need every repository now to update their guides.xml file to quote the version? Or is that only handled internally, by doing a search/replace before XML is parsed?

(Can look at that myself too, havent checked your code yet, just a reminder for me 😅)
