### ISSUE TITLE
[Bug]: url in parenthesis gets linked wrongly

### ISSUE THREAD

**Issue by tmotyl** [phpDocumentor/guides#1060]
### Summary

The url inside the parenthesis will be linked with the closing bracket included in href.

### Code snippet that reproduces the problem

```
some text (text in parenthesis https://example.com).
```

### Expected output

```
some text (text in parenthesis <a href="https://example.com" />https://example.com</a>).
```

**Comment by jaapio** [comment]
will be fixed in #1061

**Comment by linawolf** [comment]
will be fixed with the next release

**Comment by tmotyl** [comment]
Thank you
