### ISSUE TITLE
[Bug]: Readme badges are broken

### ISSUE THREAD

**Issue by stof** [phpDocumentor/guides#1070]
### Summary

The readme of all packages contain some badges. However, all poser-based badges are broken, making it look ugly in GitHub and Packagist.

Apparently, this is because the readme files use `http` URLs for badges. When loading the same URL in https, the image can be loaded (maybe camo.githubusercontent.com does not like the 301 redirect from http to https).

### Expected output

badges are displayed properly (or removed)

**Comment by jaapio** [comment]
Will be fixed in #1074
