### ISSUE TITLE
Provide a documentation website for the rendered documentation

### ISSUE THREAD

**Issue by stof** [phpDocumentor/guides#1072]
### Feature request

The documentation currently relies on the GitHub rendering of the rST files.
However, the support of rST on GitHub is only partial, and the documentation currently relies on a bunch of directives that are not supported by GitHub, making it hard to read the documentation.

It would be great to provide a documentation website built using a tool supporting rST properly (maybe phpdocumentor itself ?).

**Comment by jaapio** [comment]
Thanks for the reminder. I was working on a deployment already. You can find the docs here: https://docs.phpdoc.org/components/guides/

**Comment by stof** [comment]
@jaapio I suggest updating the readme file (maybe also in the subtree readme files) to use that URL.
