### ISSUE TITLE
Documentation for extending the compiler is broken

### ISSUE THREAD

**Issue by stof** [phpDocumentor/guides#1075]
### Summary

See https://docs.phpdoc.org/components/guides/guides/developers/compiler.html#compiler

![image](https://github.com/user-attachments/assets/1dbf4fa0-d876-44cc-a9a9-e55e12e184ca)

### Expected output

Sentences should be complete

**Comment by jaapio** [comment]
Thanks, I checked the docs some invalid references were used.
