### ISSUE TITLE
[Bug]: Tables in Markdown are not displayed correctly

### ISSUE THREAD

**Issue by linawolf** [phpDocumentor/guides#1086]
### Summary

See https://github.com/phpDocumentor/guides/pull/1085

### Expected output

See https://github.com/phpDocumentor/guides/pull/1085

**Comment by linawolf** [comment]
There is an extension for that: https://commonmark.thephpleague.com/2.5/extensions/tables/

**Comment by jaapio** [comment]
I added support for tables, but we do not have a system yet to set the alignment of a cell that can be done in markdown on a column level. I'm not sure we should add this feature.

**Comment by linawolf** [comment]
I think if we need alignment support we can make a new issue. This one is solved for now
