### ISSUE TITLE
Add text role implementations

### ISSUE THREAD

**Issue by jaapio** [phpDocumentor/guides#178]
https://docutils.sourceforge.io/docs/ref/rst/roles.html

**Comment by linawolf** [comment]
I am wondering if we can somehow use the work I put into https://github.com/doctrine/rst-parser/pull/257 to solve this

**Comment by jaapio** [comment]
I think we can use parts of it, I replaced the full SpanParser to be able to split the parser into a lexing and parsing part. 

The lexer will break the text into smaller elements, called Tokens. The parser will consume those tokens to turn them into what I now named `SpanToken` But a better name would be `InlineNodes` as that refers to the inline markup that is supported by RST. 

I would like to introduce more of these kinds of `SpanToken`, the text roles you created could be just that! We could extend the rendering of the span to transform it completely into what we have now for nodes. So we can use the same mechanism as we have for other node types.
