### ISSUE TITLE
Add doctrine-rst-parser functional build tests

### ISSUE THREAD

**Issue by linawolf** [phpDocumentor/guides#219]
In the doctrine/rst-parser we introduced a new category of functional tests that work on a complete document tree:

https://github.com/doctrine/rst-parser/tree/0.6.x/tests/Functional/tests/build

This kind of test is not supported in guides yet as far as I can tell

**Comment by jaapio** [comment]
It would be good to have some tests that are testing more than isolated nodes. So I would welcome a PR for this.
