### ISSUE TITLE
Add docinfo support

### ISSUE THREAD

**Issue by jaapio** [phpDocumentor/guides#298]
https://docutils.sourceforge.io/docs/ref/doctree.html#docinfo

https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#field-lists

**Comment by linawolf** [comment]
Currently working on the field-lists

**Comment by linawolf** [comment]
Also support special Sphinx-related field list items:

https://www.sphinx-doc.org/en/master/usage/restructuredtext/field-lists.html
