### ISSUE TITLE
Support the `class` option for directives

### ISSUE THREAD

**Issue by wouterj** [phpDocumentor/guides#302]
Per https://docutils.sourceforge.io/docs/ref/rst/directives.html#common-options , any directive with content allows a `class` option that adds custom classes to the directive's DOM element.

We rely on this in some parts of the Symfony documentation, it would great to add support for this option.

<details>
<summary>Failing test on Symfony's docs-builder tests</summary>

https://github.com/wouterj/symfony-docs-guides/actions/runs/4713936115/jobs/8359959701

```
5) SymfonyDocsBuilder\Tests\HtmlIntegrationTest::testBlocks with data set "code-blocks/terminal.rst" ('/home/runner/work/symfony-doc...al.rst', '/home/runner/work/symfony-doc...l.html')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 <span class="hljs-comment"># Civilization for DOS - my first computer game!</span></code></pre>\n
 </div>\n
 </div>\n
-<div translate="no" data-loc="1" class="notranslate codeblock codeblock-length-sm codeblock-terminal codeblock-bash hide">\n
+<div translate="no" data-loc="1" class="notranslate codeblock codeblock-length-sm codeblock-terminal codeblock-bash">\n
 <div class="codeblock-scroll">\n
 <pre class="codeblock-lines">1</pre>\n
 <pre class="codeblock-code"><code><span class="hljs-prompt">$</span>git branch -D sessions-in-db ||<span class="hljs-literal">true</span></code></pre>\n
 </div>\n
 </div>'

/home/runner/work/symfony-docs-guides/symfony-docs-guides/lib/docs-builder/tests/integration/HtmlIntegrationTest.php:29```

</details>

**Comment by linawolf** [comment]
We do support the class attribute, however the templates have to output the class attribute. You think the responsibility should lie with the template or somewhere else? However in some output formats classes do not make sense? 

See for example these tests in https://github.com/phpDocumentor/guides/tree/main/tests/Integration/tests/class-directive

**Comment by wouterj** [comment]
Yes, the `.. class::` directive works as expected (although we need to update most default directive templates in this library to use `node.classes`). The `:class:` option is not yet implemented.

See e.g. this failing test case: https://github.com/phpDocumentor/guides/compare/main...wouterj:guides:issue-302 (this option should work on almost all directives)

I discovered you already worked on a PR to add support for this option in #257
