### ISSUE TITLE
References to anchors do not work

### ISSUE THREAD

**Issue by linawolf** [phpDocumentor/guides#445]
skipped tests:
https://github.com/phpDocumentor/guides/tree/main/tests/Integration/tests/anchor-title-overriden-by-ref-title
https://github.com/phpDocumentor/guides/tree/main/tests/Integration/tests/anchor-to-title-on-another-page
https://github.com/phpDocumentor/guides/tree/main/tests/Integration/tests/anchor-to-title

**Comment by jaapio** [comment]
This is fixed by #371
