### ISSUE TITLE
Using lineno-start on code-block directive throws error

### ISSUE THREAD

**Issue by brotkrueml** [phpDocumentor/guides#684]
Using this code block:

```rst
..  code-block:: ruby
    :lineno-start: 10

    Some more Ruby code, with line numbering starting at 10.
```

The following warning is triggered:

    /opt/project/vendor/phpdocumentor/guides-restructured-text/src/RestructuredText/Directives/CodeBlockDirective.php:87
    Object of class phpDocumentor\Guides\RestructuredText\Parser\DirectiveOption could not be converted to int

**Comment by linawolf** [comment]
@brotkrueml this PR should solve this: https://github.com/phpDocumentor/guides/pull/685
