### ISSUE TITLE
previousNode returns current node

### ISSUE THREAD

**Issue by linawolf** [phpDocumentor/guides#757]
$renderContext->getIterator()->previousNode()?->getDocumentEntry();

currently Returns the current node, not the previous one

**Comment by jaapio** [comment]
There are tests for this, can you link me to the place where you have this issue? As it is unclear to me if there is a context where the code is not working as expected.

**Comment by linawolf** [comment]
Yes, please have a look at https://github.com/TYPO3-Documentation/render-guides/pull/138

If I switch to using the iterator all previous links would change from a link to the previous page to a link to the current page ("#")
