### ISSUE TITLE
Remove styles from menu node rendering

### ISSUE THREAD

**Issue by jaapio** [phpDocumentor/guides#814]
When we build the menu it contains titles, however if those titles do contain styling or hyperlinks it will break the menu rendering or behavior. We should remove all styling from the titles being used in the menu items and toctree's

**Comment by jaapio** [comment]
@linawolf I would like to have your opinion on this

**Comment by linawolf** [comment]
the titlenode has a function toString which we could use?

**Comment by jaapio** [comment]
That might make sense, I remember I introduced that for reasons.
