### ISSUE TITLE
Base Template Example.

### ISSUE THREAD

**Issue by RedUhl** [phpDocumentor/guides#82]
Could you please add the the guides a basic template is the same as the default template?
I like phpDoc, but I'd like to make some minor adjustments.    
I found sunaoka / phpDocumentor3-template-ja which adjusts the headers to Japanese.
Thank you

**Comment by linawolf** [comment]
@RedUhl please have a look at phpdocumentor/guides-theme-bootstrap  It is also quite straightforward to build your own template
