### ISSUE TITLE
Trailing Zeroes are removed from version number

### ISSUE THREAD

**Issue by linawolf** [phpDocumentor/guides#829]
If I define the version numbers in the guides.xml:

```
    <project
            title="Render guides"
            version="3.0"
            release="3.0.0"
    />
```
Version is treated as a float by the Tree Builder. The Float is later cast into a string and the trailing zero gets lost

**Comment by linawolf** [comment]
I think this is where it happens: https://github.com/phpDocumentor/guides/blob/main/packages/guides/src/DependencyInjection/GuidesExtension.php#L58

**Comment by linawolf** [comment]
@wouterj do you think you can help here? You seem to know a lot about the tree builder

**Comment by wouterj** [comment]
This unfortunately is a known limitation of the XML file loader. As all values in an XML document are strings, the XML file loader makes [an educated guess[(https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Config/Util/XmlUtils.php#L210-L239) on how to transform them into PHP types, before passing them into the Config tree for validation (the XML loader is decoupled from the config tree, so it doesn't know the `version` property is a scalar node).

I'm not really sure how we can best work around this.

**Comment by linawolf** [comment]
and version 3.10 will be turned into 3.1 :-(
