### ISSUE TITLE
Render text roles in caption of code block

### ISSUE THREAD

**Issue by brotkrueml** [phpDocumentor/guides#834]
Sphinx can render a file text role in a caption:

    ..  code-block:: console
        :caption: Directory listing of :file:`var/log/` with rotated logs

This looks like:

![image (1)](https://github.com/phpDocumentor/guides/assets/2566282/1d41c20e-0be4-4049-9a13-7576c922cdcf)

However, guides can not:

![image (2)](https://github.com/phpDocumentor/guides/assets/2566282/8f9f9066-4d68-4cd8-b140-b426b4fbe789)

**Comment by linawolf** [comment]
resolved by https://github.com/phpDocumentor/guides/pull/835
