### ISSUE TITLE
`make docs` does not work anymore

### ISSUE THREAD

**Issue by linawolf** [phpDocumentor/guides#857]
Could not open input file: tools/phpDocumentor.phar

**Comment by garvinhicking** [comment]
Hm, the makefile doesn't list a `docs` entry point, do you mean another command?

**Comment by linawolf** [comment]
Sure, line 87 in the makefile there is one, but it seems to point to non-existent phpDocumentor.phar

**Comment by jaapio** [comment]
I replaced it with a working docker command.
