### ISSUE TITLE
[Bug]: Section indexes should only render headers below the current place

### ISSUE THREAD

**Issue by brotkrueml** [phpDocumentor/guides#901]
### Summary

In Sphinx-based rendering section indexes hold only the anchors below the current place, for example:

![Bildschirmfoto vom 2024-03-04 10-14-59](https://github.com/TYPO3-Documentation/render-guides/assets/2566282/40f3f762-5561-4627-93d0-ce169cded1a3)

https://docs.typo3.org/m/typo3/reference-tsconfig/12.4/en-us/UserTsconfig/Options.html

PHP-based rendering seems to take all headers into account:

![Bildschirmfoto vom 2024-03-04 10-15-54](https://github.com/TYPO3-Documentation/render-guides/assets/2566282/fbcbc170-50cb-452e-bb13-9705c93eb459)

https://docs.typo3.org/m/typo3/reference-tsconfig/main/en-us/UserTsconfig/Options.html

MInd the additional "Properties" anchor in the last example.

### Code snippet that reproduces the problem

```
Properties
==========

..  contents::
    :depth: 2
    :local:

additionalPreviewLanguages
--------------------------

some text

alertPopups
-----------

another text
```

should not render "Properties"

### Expected output

* additionalPreviewLanguages
* alertPopups

**Comment by linawolf** [comment]
... if `:local:` is set
