### ISSUE TITLE
[Bug]: Space missing after bold followed by a reference

### ISSUE THREAD

**Issue by brotkrueml** [phpDocumentor/guides#922]
### Summary

The following rst:

```rst
**all** :ref:`data <tce-data>`
```
produces the following code:

```html
<strong>all</strong><a href="../Database/Index.html#tce-data">data</a>
```

Obviously, a space is missing after `</strong>`.

The same happens for italic:

```rst
*all* :ref:`data <tce-data>`
```

### Code snippet that reproduces the problem

See summary

### Expected output

A space between the closing tag and the link

**Comment by wouterj** [comment]
I've had similar cases in the past when testing the Symfony documentation. I believe all those were caused by our own templates, and not by a bug in Guides.

You might want to check if this is reproducible in a test in this repository (or using the default theme).

**Comment by linawolf** [comment]
I am able to reproduce this with the guides default templates... :-(
