### ISSUE TITLE
[Bug]: Failed connection to plantuml server should not abort the rendering

### ISSUE THREAD

**Issue by brotkrueml** [phpDocumentor/guides#965]
### Summary

Currently, when the plantuml server is not available an error is thrown and the whole rendering is aborted. Therefore, I cannot check my changes locally, which are totally unrelated to this problem.

### Code snippet that reproduces the problem

Add www.plantuml.com to your /etc/hosts with 127.0.0.1 or something similar.

### Expected output

Instead a warning should be output, and the rendering should be finished.

For CI tasks which push those to a server, the warnings should abort the process, which would then be fine.

**Comment by brotkrueml** [comment]
And: a custom plantuml server is not the solution as it has to be maintained and updated regularly, which adds burdon to the projects who use guides. And also this server can be down which is annoying for users which then cannot render their documentation locally.

**Comment by jaapio** [comment]
I added a test case which shows warnings are triggered when the server is unreachable. If this is an issue on your side I would recommend to investigate the configuration of the httpclient. However I do not think it is changed on the typo3 side.

@linawolf can you please investigate what is going on your side?

**Comment by linawolf** [comment]
@brotkrueml what error message do you get?

**Comment by brotkrueml** [comment]
I wrote that some weeks ago in the Slack channel; That the server is not reachable. It occured only seldomly - but then is very annoying as the whole rendering breaked.

**Comment by linawolf** [comment]
We do have a test-case in the guides, that shows if the server is not reachable there is a warning. So there must be some other issue here. Are there any error messages / exceptions when the rendering is breaking?

**Comment by brotkrueml** [comment]
There were already two commits merged after creating this issue. Maybe it is fixed now.

**Comment by linawolf** [comment]
So if it happens again please record what kind of error is displayed and open a new issue
