### ISSUE TITLE
[Bug]: Using local in contents directive should only show heading inside the section

### ISSUE THREAD

**Issue by brotkrueml** [phpDocumentor/guides#966]
### Summary

Using

```rst
.. contents::
   :local:
```

should only show headings inside this section, omitting the heading of this section. This is wrong as it displayes "Properties":

![Bildschirmfoto vom 2024-04-01 15-12-57](https://github.com/phpDocumentor/guides/assets/2566282/ced3fa2f-b0f7-4d7f-8fbe-2b9a8fdbfaa5)

See: https://docutils.sourceforge.io/docs/ref/rst/directives.html#table-of-contents

> Entries will only include subsections of the section in which the directive is given.

### Code snippet that reproduces the problem

```rst
Main section
============

.. contents::
   :local:

Sub section 1
-------------

Text

Sub section 2
-------------
```

### Expected output

- Sub section 1
- Sub section 2

**Comment by jaapio** [comment]
I'm sorry, I cannot reproduce this issue with the latest version of our code. Could it be that you need an update? 

@linawolf

**Comment by linawolf** [comment]
Was solved by https://github.com/phpDocumentor/guides/pull/961
